# Default values for web-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
maxUnavailable: 0
revisionHistoryLimit: 5
image:
  version: 1.0
  repository: local
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  isAlivePath: /
ingress:
  enabled: false
  hosts:
    - chart-example.local
resources:
  limits:
   cpu: 500m
   memory: 600Mi
  requests:
   cpu: 100m
   memory: 128Mi
autoscale:
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 50
