team: alldaydevops
nameOverride: harry-server
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - harry.alldaydevops.local
image:
  version: 1.0
  repository: omerlh
  pullPolicy: IfNotPresent
service:
  internalPort: 80
  isAlivePath: /