apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "web-api.name" . }}
  namespace: all-day-devops
  labels:
    app: {{ template "web-api.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    company: Soluto
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: {{ template "web-api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}/{{ template "web-api.name" . }}:{{ .Values.image.version }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 10 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.service.isAlivePath }}
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.service.isAlivePath }}
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          envFrom:
           - configMapRef:
              name: {{ template "web-api.name" . }}
        {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ toYaml .Values.imagePullSecrets }}
        {{- end }}
       {{- if .Values.volumeMounts }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
        {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
